version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: Europe/Berlin
      
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    versioning-strategy: increase
